name: "Build"
on:
  push:
    branches:
      - master
  schedule:
    # Random time each week.
    - cron:  '45 9 * * 5'

jobs:
  build:
    uses: silvenga-docker/building/.github/workflows/publish-github.yaml@master
    secrets: inherit
